export const apiConfig = {
  // BASE_URL: "https://thegranduchy.com/backend/v1.0.0/apis",
  BASE_URL: "https://grand-duchy-ebook-backend.vercel.app/v1.0.0/apis",
  // BASE_URL: "http://localhost:5835/v1.0.0/apis",
  USER: {
    PROVIDER_LOGIN: "/users/providerLogin",
    UPDATE_FONT: "/users/updateFont",
    UPDATE_ACTIVE_TIME: "/users/updateTotalActiveTime",
    GET_ALL: "/users/getAllUsers",
    GET_ACTIVE_TIME: "/users/getTotalActiveTime",
  },
  BOOK: {
    UPLOAD: "/books/uploadBook",
    UPLOAD_ACT: "/books/addAct",
    UPLOAD_CHAPTER: "/books/addChapter",
    UPLOAD_EPISODE: "/books/addEpisode",
    UPDATE_BOOK: "/books/updateBook",
    GET_ALL: "/books/getAllBooks",
    GET_BY_ID: "/books/getBookById",
    GET_EPISODE_COUNT_BY_ID: "/books/getEpisodeCountById",
    UPDATE: "/books/updateBook",
    DELETE: "/books/deleteBook",
    GET_TITLES: "/books/getBooksTitle",
    GET_LATEST_EPISODE: "/books/getLatestEpisode",
    GET_FORMATTED_BOOK_BY_ID: "/books/getFormattedBookById",
  },
  SUMMARY: {
    ADD: "/summary/addSummary",
    GET_ALL: "/summary/getAllSummary",
    GET_BOOKS_SUMMARY: "/summary/getSummariesByBook",
    UPDATE: "/summary/updateSummary",
    DELETE: "/summary/deleteSummary",
  },
  READ_LIST: {
    CREATE: "/readList/createReadList",
    GET_LATEST: "/readList/getLatestReadList",
    GET_DETAILS: "/readList/getReadListDetails",
  },
  CHARACTER: {
    ADD: "/character/uploadCharacter",
    GET_ALL: "/character/getAllCharacters",
    GET_RANDOM: "/character/getRandomCharacter",
    UPDATE: "/character/updateCharacter",
    DELETE: "/character/deleteCharacter",
  },
  QUOTE: {
    ADD: "/quotes/uploadQuote",
    GET_ALL: "/quotes/getAllQuotes",
    GET_RANDOM: "/quotes/getRandomQuote",
    UPDATE: "/quotes/updateQuote",
    DELETE: "/quotes/deleteQuote",
  },
  NOTE: {
    ADD: "/notes/uploadNote",
    GET_ALL: "/notes/getAllNotes",
    GET_LATEST: "/notes/getLatestNote",
    UPDATE: "/notes/updateNote",
    DELETE: "/notes/deleteNote",
  },
  TIMER: {
    UPDATE: "/timer/updateOrCreateTimer",
    GET: "/timer/getUpcomingTime",
  },
};
